### ISSUE TITLE
CC0017 Change to auto property fix all not working

### ISSUE THREAD

**Issue by thorgeirk11** [code-cracker/code-cracker#514] opened 2015-09-17 20:07 UTC
The code fix for CC0017 doesn't change all instances.

If the code fix is run on a document containing the following code:
```CSharp
private int x;
private int y;
public int X
{
    get { return x; }
    set { x = value; }
}

public int Y
{
    get { return y; }
    set { y = value; }
}
```
It results in the following:
```CSharp
private int x;
public int X
{
    get { return x; }
    set { x = value; }
}
public int Y { get; set; }
```

But of course it should be: 
```CSharp
public int X { get; set; }
public int Y { get; set; }
```

I found this out when I was working on #500 and #512 but I am unsure how to fix it so I decided to just make a Issue out of it.

**Comment by giggio** [comment] 2015-09-20 03:40
Bug confirmed. This should be fixed on the `master` branch. It is up for grabs.

**Comment by giggio** [comment] 2015-09-20 04:06
BTW, there is already an ignored test on the code for this specific bug.

**Comment by adraut** [comment] 2015-10-10 04:42
Almost seems like a threading issue.  Sometimes the result is
```C#
private int y;

public int X { get; set; }

public int Y
{
    get { return y; }
    set { y = value; }
}
```
and other times it's
```C#
private int x;

public int X
{
    get { return x; }
    set { x = value; }
}

public int Y { get; set; }
```

The fixer does request the root a few times throughout the process, but I've added debug writes in the fix process to see what the document looks like at each step and it does not appear that one fix for a property is interacting with another.

Looks like it could possibly be due to https://github.com/dotnet/roslyn/issues/4416.  It appears that maybe some trivia is being seen as changed by multiple fixes and only one gets merged.

It's very easy to see with the existing test case that was previously being skipped.
```
private int x = 42, y;

public int X
{
    get { return x; }
    set { x = value; }
}

public int Y
{
    get { return y; }
    set { y = value; }
}
```

Will randomly return
```
private int y;

public int X { get; set; } = 42;

public int Y
{
    get { return y; }
    set { y = value; }
}
```

Or 
```
private int x = 42;

public int X
{
    get { return x; }
    set { x = value; }
}

public int Y { get; set; }
```

**Comment by giggio** [comment] 2015-10-16 02:43
@adraut The problem is that the batch fixer only solves non conflicting changes, and this is creating a conflict. It does not matter that it is not deterministic, it would only fail in a deterministic way, but it would still fail.
What is needed to fix this is work in a way that all changes are merged together in an intelligent way. This demands code that we write, the batch fixer is unable to conciliate this problems.
What I noticed is that whenever 2 or more code actions change the same node the batch fixer will throw one of the changes away. We simply need to solve this problem.

**Comment by giggio** [comment] 2015-10-26 01:31
I am working on it.

**Closed** 2015-11-02 00:44 UTC
Labels: 2 - Working, bug, C#, code-fix
