### ISSUE TITLE
CC0033 : false positive - cannot handle elvis operator

### ISSUE THREAD

**Issue by RachelDavids** [code-cracker/code-cracker#858] opened 2017-01-05 14:01 UTC
````csharp
	public class Class1

	: IDisposable

	{

		private Helper  _helper = new Helper();
		// ...........................^^^^^^^^^^^^^^^;

		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				_helper?.Dispose();
			}
		}

		public void Dispose()
		{
			Dispose(true);
		}

		private sealed class Helper
			: IDisposable
		{
                       [CanBeNull]
			private IDisposable _item = new Task(() => { });
    		       // ....................................^^^^^^^^^^^^^^^^^;
			public void Dispose()
			{
				_item?.Dispose();
			}
                        /* other code that sets _item to null */
		}
	}
````
Under both declarations CC0033 is indicated.

In both cases, the Fix is unnecessary AND introduces a potential bug by not including the elvis operator.

**Comment by giggio** [comment] 2017-01-07 19:51
This is a duplicate of #848, which is already fixed and will be released soon. Thanks for the report @RachelDavids .

**Closed by giggio** 2017-01-07 19:51 UTC
Labels: duplicate
