### ISSUE TITLE
Bug, nameof fix doesn't work well with operators

### ISSUE THREAD

**Issue by SergeyZhurikhin** [code-cracker/code-cracker#620] opened 2015-12-13 18:52 UTC
For  "a"  in method Add CodeFix returns **nameof**(a), but in operator+  returns **nameof**(**MyClass**):
```CS
    public class MyClass
    {
        public MyClass Add(MyClass a, MyClass b)
        {
            var str = "a"; //Fix to: nameof(a)
            return null;
        }
        public static string operator +(MyClass a, MyClass b)
        {
            var str = "a"; //Fix to: nameof(MyClass)
            return null;
        }
    }

**Comment by carloscds** [comment] 2015-12-14 12:17
@SergeyZhurikhin Bug confirmed.

**Comment by giggio** [comment] 2015-12-14 14:33
This is a duplicate of #594, and it is already being fixed. I just verified the PR and it fixes this case as well.

**Closed by giggio** 2015-12-14 14:33 UTC
Labels: duplicate
