### ISSUE TITLE
NULL check when it is not necessary

### ISSUE THREAD

**Issue by raphaelm22** [code-cracker/code-cracker#807] opened 2016-07-11 14:22 UTC
```csharp
public class Foo
{
    private Func<object, bool> _filter;

    public void Bar()
    {
        var myObject = new object();

        if (_filter == null || _filter(myObject))
            Console.WriteLine("Test");
    }
}
```
The Code-Crack is saying that there may be a NullReferenceException in the IF. But it is not true in this situation.

![a](https://cloud.githubusercontent.com/assets/11078528/16733861/a5e8e4b8-4759-11e6-988b-d6312bac28ff.png)

**Comment by giggio** [comment] 2016-08-08 02:15
Duplicate of #779, I added your example to the test case there.

**Closed by giggio** 2016-08-08 02:15 UTC
