### ISSUE TITLE
CC0001: Show it only where appropriate

### ISSUE THREAD

**Issue by TsengSR** [code-cracker/code-cracker#783] opened 2016-04-17 14:20 UTC
#Bug

In my opinion, the CC0001 should only be shown in cases which makes sense and where type declaration is redudant and not show warnings where it's not redudant and were var wouldn't hide information important for reader of the code. 

For example, the warning should come only when there is a new operator on the right side. 

````csharp
//the code that reproduces the bug
List<string> tags = new List<string>();
User user = repository.Get<User>(5); // where repository is a generic repository
IEnumerable<User> users = repository.GetAll<User>(); // where repository is a generic repository
List<string> tags = GetTags(); 
int count = 0;
````

Current warnings and fix suggestions: 

````csharp
var tags = new List<string>();
var user = repository.Get<User>(5);
var users = repository.GetAll<User>(); // where repository is a generic repository
var tags = GetTags();
var count = 0;
````

Expected warnings and fix suggestions:

````csharp
var tags = new List<string>();
var user = repository.Get<User>(5);
IEnumerable<User> users = repository.GetAll<User>();
List <string> tags = GetTags(); 
int count = 0;
````

Both suggestions are related to Code Reviews. 

The reason for this is, that ```var tags = new List<string>();``` hides no information, because it's obvious from the assignment that the type of tags is ```List<string>```. On ```var tags = GetTags();``` however, the information is hidden away as it's not obvious that ```GetTags()``` may have  ```List<string>``` as return type. It could also be ```List<Tag>``` and we won't see it until we inspect the tooltips. 

For scalar types, var shouldn't be shown as warning for several reasons, main one being being that in code reviews it becomes harder to track changes, i.e. if ```var count = 0``` gets changed to ```var count = 0.0``` (or change from float to decimal whlie using var)  it may have impact on further calculations. 

Last but not least, if a generic method type matches the type left of the assignment operator, the warning should suggest using var. If it do not match, it should not suggest it. 

Above are two samples of that:

````csharp
var user = repository.Get<Tag>(); // returns T
IEnumerable<User> users = repository.GetAll<User>(); // returns IEnumerable<T>
````
Having ```User``` feels redudant in ```User user = repository.Get<User>(5); // returns T``` when the return type is the type used in ```Get<T>``` and brings no additional information from a code review perspective.

in ```IEnumerable<User> users = repository.GetAll<User>(5);``` it's different, because ```GetAll<User>()``` doesn't return ```User``` as may think by quick reading of th code and while "GetAll" suggest it's a collection, we don't know if it's ```User[]```, ```IEnumerable<User>```, ```IList<User>``` or some custom implementation maybe called ```UserCollection```, so having a var here will be a loss of information. 

This samples above match with the overall guidelines on when and how to use the ```var``` keyword. It should only be used, when the declaration on the left side is redudant.

Or at least an option to enable/disable between the current and the described behaviour, with preference to have this behaviour as default.

**Comment by giggio** [comment] 2016-04-18 04:41
I disagree, I like `var` everywhere. But I would like to know what everyone else thinks, other users, @code-cracker/collaborators and @code-cracker/core.

**Comment by AmadeusW** [comment] 2016-04-18 06:00
@TsengSR shows a very convincing case but it ultimately leads to inconsistent code. I like either having all variables typed or all of them being `var`.
The reason I use an IDE and not just a text editor is for the code to say `var` and for a tooltip to tell me more. So I'm on the `var` side.

**Comment by TsengSR** [comment] 2016-04-18 06:12
It's not about personal preferences, I tend to do things to that may or may not be the best practice depending on where you work or if you work with others (i.e. one-liner if blocks w/o curly bracers). This one is generally about best practices and code readability, something important in a professional field, where code is reviewed by a different person than the one who wrote the code. 

There vars are pretty bad for the reasons called above. I personally though only use var when on linq expressions and on inintalizations of complex type like dictionary or nested generics (Dictionary<string, List<User>>) where it adds no extra information. 

The original purpose why ```var``` was introduced was because of annonymous types used in LINQ. 

I'd like quoting MSDN here. 

https://msdn.microsoft.com/en-us/library/bb384061%28v=vs.140%29.aspx

> You may find that var can also be useful with query expressions in which the exact constructed type of the query variable is difficult to determine. This can occur with grouping and ordering operations.
> 
> **The var keyword can also be useful when the specific type of the variable is tedious to type on the keyboard, or is obvious, or does not add to the readability of the code**. One example where var is helpful in this manner is with nested generic types such as those used with group operations. In the following query, the type of the query variable is IEnumerable<IGrouping<string, Student>>. As long as you and others who must maintain your code understand this, there is no problem with using implicit typing for convenience and brevity.
> C#
> 
> ````csharp
> // Same as previous example except we use the entire last name as a key.
> // Query variable is an IEnumerable<IGrouping<string, Student>>
>  var studentQuery3 =
>      from student in students
>      group student by student.Last;
> ````
> **However, the use of var does have at least the potential to make your code more difficult to understand for other developers. For that reason, the C# documentation generally uses var only when it is required.**

**Comment by AlbertoMonteiro** [comment] 2016-04-18 10:40
I want ‘var‘ everywhere

**Comment by thomaslevesque** [comment] 2016-04-18 11:18
I want `var` where I want it, and nowhere else. Since no analyzer (except one made specifically for me) can guess where I want it, I usually disable `CC0001`.

**Comment by LoRdPMN** [comment] 2016-04-20 12:47
IMO `var` should be used only where it doesn't "hides" the type, because of this I am suppressing this warning in all my projects at project level.

**Comment by julianosaless** [comment] 2016-04-20 13:20
I think when we use `var` the code it becomes is more readable.

List<string> tags = new List<string>();

var tags = new List<string>();

**Comment by akamud** [comment] 2016-04-20 13:36
I believe @TsengSR's explanation on where to use `var` is right on spot. I also prefer using `var` that way, but I've worked on teams that use `var` everywhere.

Also, from this discussion it is very clear that this varies from team to team, and there is no right answer, now the problem is: how can we provide a helpful diagnosis for both cases? Right now I do the same as @thomaslevesque and turn it off when I don't want it.

Creating a new diagnosis would conflict with `CC0001`.

**Comment by AlbertoMonteiro** [comment] 2016-04-20 13:50
In a clean code, a line with more than 100 characters is bad, so if I can use a reserved word that is pretty small I will.
There are many others languages that lack type definition, and they wont be less readable because they dont have it.
If you want a readable code, name your variable properly, don't expect the type definition be your savior for readable code.

**Comment by wmjordan** [comment] 2016-04-27 09:02
I want `var` everywhere except the following situation:

````CSharp
int x = 1, y = 1, z = -1;
````

**Comment by thorgeirk11** [comment] 2016-04-27 10:54
In my opinion this feature is so dependent on the users preferences that it is really hard to make a generic rule set. 

Is there anyway to have options/settings for an analyser? if not then maybe there really is nothing to be done. it's better to have a simple rule for the analyser and those who don't like it should disable it.

**Comment by akamud** [comment] 2016-04-27 14:09
I think it is very clear that this is user's preference. Even Microsoft's teams showed to have some disagreement about this in some Channel9 videos.

**Comment by jwooley** [comment] 2016-04-27 14:39
@wmjordan In your example, I would actually recommend adding a analyzer to detect the multiple declarations and split them into separate lines instead (with var).

For me the place where explicit typing is helpful is where you want to work with a base class/interface rather than the inferred actual type.

@thorgeirk11 the VS "15" preview from Build did include some configuration capabilities on analyzers, but they are hard coded at the moment. We're talking with the team about potential extensibility points for third party analyzer configuration. They're still pretty early in the design process on this one.

Overall I tend to side on the opinion of continuing to offer the analyzer and allowing the user to tweak the severity (error/warning/info/none) in the ruleset until the configuration option is available.

**Comment by jwooley** [comment] 2016-04-27 18:12
FWIW, the current C# submission guide for Roslyn states the following preferred behavior:

> We only use  var  when it's obvious what the variable type is (i.e.  var stream = new FileStream(...)  not  var stream = OpenStandardInput() 

Of course determining what is obvious is subjective as well, so making an analyzer for this would be even harder and still not solve the issue of teams not agreeing with the application of the rule.

**Comment by TsengSR** [comment] 2016-05-06 09:36
> Of course determining what is obvious is subjective as well, so making an analyzer for this would be even harder and still not solve the issue of teams not agreeing with the application of the rule.

Well, actually it's pretty easy. There are two obvious cases:

1. When there is a ```new``` operator on the right side of the assignment
2. In case of a generic method, when the return type of the method equals the generic parameter, i.e. ```public T Get<T>(int id)``` and only then when the generic type is not removed or can't be removed. 

 For example ```public T DoSomething<T>(T object)```. 
 In this case, the generic type can be removed. ```Sometype result = someClass.DoSomething<T>(otherSometype)``` and ```Sometype result = someClass.DoSomething(otherSometype)``` are equal in this case, since the generic parameter is determined by the passed in parameters type. The only difference is that in ```var result = someClass.DoSomething(otherSometype)``` it's not obvious what type ```result``` has, where in ```Sometype result = someClass.DoSomething(otherSometype)``` and in ```var result = someClass.DoSomething<Sometype>(otherSometype)``` it is 

 The second example is a bit special, as DoSomething could also return an IEnumerable<Sometype>, in this case the ```var``` should not be suggested, because return type ```IEnumerable<Sometype>``` differs from the Generic type which is ```Sometype```.

I personally wouldn't suggest using ```var``` on types like int/float/double/decimal because there is no need. They are generally pretty short and declarative

**Comment by giggio** [comment] 2016-08-07 20:01
We seem very much divided. The ones that don't want this analyzer can disable it. I don't think we will ever find an ideal analyzer that pleases everyone. And there is no way to configure an analyzer at this moment.
I am closing this issue until we have a way to configure analyzers.

That said, I think there is room to split `CC0001` into more diagnostic ids, keep them all enabled, and then the user can disable what they don't like. @TsengSR, why don't you start, send us a PR that splits it into the cases you prefer. Make it easy to evolve it later, please.

**Closed by giggio** 2016-08-07 20:01 UTC
Labels: wontfix

**Comment by GGG-KILLER** [comment] 2017-09-24 08:15
I'd like to shine some light on this issue as VS2017 has the Code Style settings for C# which can make `CC001` redundant on this extension:
![image](https://user-images.githubusercontent.com/5892127/30780691-660a58c0-a0e7-11e7-81f5-0835d96a367c.png)

**Comment by TsengSR** [comment] 2017-09-24 13:05
Yes, I personally think both of the analyzers are obsolete now with Microsoft Code Analysis extension. 

These typically don't map to the VS 2017 ones (CC0001 seems to be for reference types, including string, where CC0105 is for value types). What I find myself doing of recently is putting both warnings on ignore either via csproj or via global suppression file

**Comment by giggio** [comment] 2017-09-28 19:00
The `IDExxxx` diagnostics only work in Visual Studio, they won't show up in VS Code.

**Comment by GGG-KILLER** [comment] 2017-09-28 19:13
Yes, but Code Cracker isn't available for VS Code, at least not in my search: https://marketplace.visualstudio.com/search?term=Code%20Cracker&target=VSCode&category=All%20categories&sortBy=Relevance

And `CC0001` and `CC0105` could be disabled for Visual Studio builds but not VSCode builds.

**Comment by AlbertoMonteiro** [comment] 2017-09-28 19:14
@GGG-KILLER code cracker can be instaled as a nuget package, and the it will work in VS Code

**Comment by GGG-KILLER** [comment] 2017-09-28 19:49
Yes @AlbertoMonteiro but (in my opinion) as it was not placed in the VS Code marketplace nor do I see any mentions of VS Code in README, VS Code is not officially supported (yes, you can run Code Cracker on it but it's not announced as a VS Code extension).
So one wouldn't expect that VS users won't have obsolete analyzers deprecated and removed because of an unsupported platform.

**Comment by TsengSR** [comment] 2017-09-28 20:29
@giggio: The analyzers from Microsoft Code Analysis 2017 are also available as NuGet packages https://github.com/dotnet/roslyn-analyzers, so they should work everywhere too where NuGet analyzers are supported

**Comment by thomaslevesque** [comment] 2017-09-28 23:09
Roslyn analyzer packages don't really work in VSCode... You will get diagnostics at build time, because the compiler supports analyzers, but VSCode won't show real-time diagnostics or code fixes in the editor. For that to work, support for analyzers needs to be added to OmniSharp (https://github.com/OmniSharp/omnisharp-vscode/issues/43)
