### ISSUE TITLE
CC0039 must not be raised if the variable is declared inside the loop

### ISSUE THREAD

**Issue by wertzui** [code-cracker/code-cracker#519] opened 2015-09-21 10:05 UTC
foreach(var a in b)
    {
        var text = "foo";
        text += "bar";
    }

Will raise CC0039 which is incorrect.
In addition the refactoring will fail because text is declared inside the loop.

**Comment by giggio** [comment] 2015-09-30 02:14
This is a duplicate of #485 and is already fixed. We will release a new RC soon.

**Closed by giggio** 2015-09-30 02:14 UTC
