### ISSUE TITLE
Remove Unused Method (CC0068) shown on method in use.

### ISSUE THREAD

**Issue by thorgeirk11** [code-cracker/code-cracker#367] opened 2015-06-01 16:22 UTC
The CC0068 is being shown on a method that has references on it.
I think it might be because of the type parameter.

![image](https://cloud.githubusercontent.com/assets/2693474/7917430/eadb51de-0879-11e5-866b-db15b83cc98f.png)

Here is the code:
```CSharp
static void Main(string[] args)
{
    var guid = MyNew<Guid>();
    var list = MyNew<List<int>>();
}

private static T MyNew<T>() where T : new() => new T();
```

Is this the same as #343 ?

**Comment by giggio** [comment] 2015-06-01 17:01
@thorgeirk11 It looks like it, are you using the latest version? We just published alpha6.

**Comment by giggio** [comment] 2015-06-01 17:08
Ok, I have just confirmed that this bug is fixed, this code is not generating a diagnostic on the latest version (both nuget and extension, check both). I am closing the issue, please check with the latest version and if you still get the diagnostic let us know and we will try to dig deeper.

**Closed by giggio** 2015-06-01 17:08 UTC

**Comment by thorgeirk11** [comment] 2015-06-02 11:22
Alright, I was using alpha5 and have now updated to alpha6.
