### ISSUE TITLE
Virtual method call in constructor

### ISSUE THREAD

**Issue by andrecarlucci** [code-cracker/code-cracker#203] opened 2015-01-06 20:25 UTC
This:

```csharp
    public class Person
    {
        public Person(string foo) {
            DoFoo(foo);
        }

        public virtual void DoFoo(string foo) { ... }
    }
```

Category: `Usage`
Diagnostic Id: `CC0067`
Severity: `Warning`

**Comment by andrecarlucci** [comment] 2015-01-06 20:25
I'll do it!

**Comment by sharwell** [comment] 2015-01-06 20:36
Should this be in the **Usage** category since it is a duplicate of [CA2214](http://msdn.microsoft.com/en-us/library/ms182331.aspx)?

**Comment by andrecarlucci** [comment] 2015-01-06 20:52
I got this from resharper, I didn't notice it was also on Code Analysis. 
So yes, it should. I edited there, thanks @sharwell !

**Comment by giggio** [comment] 2015-01-10 22:09
Go for it, @andrecarlucci.

**Comment by giggio** [comment] 2015-02-16 04:46
@andrecarlucci How is this coming?

**Comment by andrecarlucci** [comment] 2015-02-18 18:48
I finally finished (this saturday) my project with Intel and have some free
time :)

André Carlucci
twitter/andrecarlucci
Microsoft MVP
Intel Innovator
www.andrecarlucci.com

**Comment by giggio** [comment] 2015-02-18 19:13
Anxiously awaiting for your PR! :)

**Closed** 2015-04-07 17:40 UTC
Labels: 2 - Working, analyzer, C#, enhancement
