### ISSUE TITLE
BUG: CC0022 DisposableVariableNotDisposedAnalyzer: False positive when using null coalescing

### ISSUE THREAD

**Issue by oysteinkrog** [code-cracker/code-cracker#878] opened 2017-02-22 10:41 UTC
#Bug

This should not trigger CC0022:
````csharp
public class Test : IDisposable
{
    private IDisposable _stream;

    public void Update()
    {
        _stream = _stream ?? new MemoryStream();
    }

    public void Dispose()
    {
        _stream.Dispose();
    }
}
````

**Comment by carloscds** [comment] 2017-02-22 11:22
@oysteinkrog Bug confirmed!

**Comment by giggio** [comment] 2017-03-13 02:39
Duplicate of #870.

**Closed by giggio** 2017-03-13 02:39 UTC
Labels: 1 - Ready, analyzer, bug, C#, up-for-grabs
