### ISSUE TITLE
Code fix in CC0014 TernaryOperatorAnalyzer remove comments

### ISSUE THREAD

**Issue by filippobottega** [code-cracker/code-cracker#551] opened 2015-10-12 10:35 UTC
Code fix for CC0014 TernaryOperatorAnalyzer is not compatible with comments in VB code.
Example:
Original code:
        If stackFrameItem.GetMethod.DeclaringType Is Nothing Then
          declaringType = "<Nothing>"   'MLHIDE
        Else
          declaringType = stackFrameItem.GetMethod.DeclaringType.ToString
        End If
Fixed code:
        declaringType = If(stackFrameItem.GetMethod.DeclaringType Is Nothing, "<Nothing>", stackFrameItem.GetMethod.DeclaringType.ToString)

 'MLHIDE comment was deleted.

Regards,
    Filippo Bottega

**Comment by paul1956** [comment] 2015-10-12 10:47
I saw this as well but what is the expected behavior. I created a separate refactoring to move inline comments to before the beginning of the statement. Then you can use this refactoring but is that even the correct behavior?

**Comment by filippobottega** [comment] 2015-10-12 12:57
I don't think so because in my example 'MLHIDE is a comment generated by Multi-Language for Visual Studio http://www.jollans.com/tiki/tiki-index.php and needs to be inserted at the end of the code line.
Is it possible to create two different refactorings?

**Comment by jwooley** [comment] 2015-10-12 13:29
Multiple possible fixes would sound like a good option. With the changes in VB to support comments after implicit line continuation, you should be able to offer a fix along the lines of – 

 

Dim x = If(true,

                   1, ‘ Comment

                   2)

 

I’m not sure however if that construct would support the needs of the Multi-Language tool that you are needing since this comment is not at the end of an operation.

 

Also, I’m not sure how much more concise this option is over the standard If .. Then block syntax and warrants a conversion from block to ternary syntax.

**Comment by filippobottega** [comment] 2015-10-12 13:47
In my case I think that this is better solution:

Dim x = If(true, 1, 2)  ‘ Comment 

Moreover I'm trying to understand when is meaningful to apply CC0014 fix because I'm changing:
Dim x = If(true, 1, 2) 
to:
Dim x = If(true, 
1, 
2)
because If(true, 1, 2) is difficult to read in case 1 and 2 are long more then 20 characters.

Thanks to all for your support! 

Best regards,
  Filippo Bottega.

**Comment by jwooley** [comment] 2015-10-12 16:42
@filippobottega the multi-line option was proposed in order to retain the comment trivia associated with both the if and else side of the original code. It wouldn't be necessary if you concatenate all trivia at the end.

**Comment by filippobottega** [comment] 2015-10-13 07:26
@jwooley I agree, I only suggested to use multi-line option when there aren't comments but 1 and 2 are too long to put them in a single line.

**Comment by giggio** [comment] 2015-10-16 03:44
Bug confirmed.
Here is a simpler case:

````vb
        Sub Foo()
            Dim i
            If 1 > 2 Then
                i = 0 'comment 1
            Else
                i = 1 'comment 2
            End If
        End Sub
````

Should be fixed to:

````vb
        Sub Foo()
            Dim i
            i = If(1 > 2, 0, 1) 'comment 1 'comment 2
        End Sub
````

Agreed?

**Comment by filippobottega** [comment] 2015-10-16 08:04
Yes!!!

**Comment by giggio** [comment] 2015-10-16 13:53
Being worked on by @jwooley along with #550.

**Comment by giggio** [comment] 2015-11-01 23:29
Hey @jwooley, how is this and #550 coming?

**Closed** 2015-11-07 14:39 UTC
Labels: 2 - Working, bug, code-fix, VB
