### ISSUE TITLE
CC0013 Fix Error

### ISSUE THREAD

**Issue by filippobottega** [code-cracker/code-cracker#553] opened 2015-10-14 12:19 UTC
For example:
    If nonClsCompliantIdentifiers.Contains(inputType.FullName.ToUpper) Then
      Return GetType(Object)
    ElseIf nonClsCompliantIdentifiers.Contains(Replace(inputType.FullName, "[]", "").ToUpper) Then
      Return GetType(Object())
    Else
      Return inputType
    End If

Is different from:

    Return If(nonClsCompliantIdentifiers.Contains(inputType.FullName.ToUpper), GetType(Object), inputType)

**Comment by jwooley** [comment] 2015-10-14 12:23
I recommend that we not report this analyzer in cases where an ElseIf clause is present.

**Comment by giggio** [comment] 2015-10-16 03:55
This is a duplicate of #552.

**Closed by giggio** 2015-10-16 03:55 UTC
