### ISSUE TITLE
Bug: DisposableVariableNotDisposedCodeFixProvider throws when object creation is being passed as an argument (CC0022)

### ISSUE THREAD

**Issue by davebeaumont** [code-cracker/code-cracker#409] opened 2015-07-21 13:36 UTC
When using this extension on Visual Studio Professional 2015.  On Existing and new Projects.
I, and a few work colleagues receive multiple errors when clicking the yellow Bulb.

After enabling them, the same error occurs.

Screenshot attached.
![codecracker](https://cloud.githubusercontent.com/assets/13435595/8801924/c8f7c620-2fb5-11e5-8e72-65d249a53f7a.PNG)

**Comment by giggio** [comment] 2015-07-21 15:03
@davebeaumont What VS 2015 version are you using? RTM? If it is RTM it will not work and raise all types of errors. We will release a version compatible with RTM today. AFAIK these analyzers are not raising errors, I need an specific solution where the problem is raised for each, if you can help us pinpoint the problem.

**Comment by davebeaumont** [comment] 2015-07-21 15:23
@giggio Thanks for your help and such a quick reply, I can confirm this is RTM.  I will try again after the next release.  Thanks again.

**Comment by giggio** [comment] 2015-07-21 16:20
Ok, I will close the issue. If you find the problem on the next version let us know.

**Comment by giggio** [comment] 2015-07-23 02:04
@davebeaumont Nugets and Extensions have been updated to work with RTM. Current version is 1.0.0-rc1. Please try it out and let us know if you find any problem.

**Comment by davebeaumont** [comment] 2015-07-23 08:45
This is now working well after updating, however I have noticed one small issue this morning that is generating the same error as in the above screenshot.
Code example is: 

       static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1()); --This Line States Form1 should be disposed
        }

Once clicking the lightbulb I get: 
![formdispose](https://cloud.githubusercontent.com/assets/13435595/8846486/89061ea2-311f-11e5-9579-d426fac51625.PNG)

**Comment by giggio** [comment] 2015-07-23 13:44
Bug confirmed.

**Comment by giggio** [comment] 2015-07-23 13:47
To repro:

````csharp
Method(new MemoryStream());
````

**Comment by giggio** [comment] 2015-07-29 00:56
The disposable problem is being tracked on #432.

**Closed by giggio** 2015-07-29 00:56 UTC
Labels: 1 - Ready, bug, C#, code-fix, up-for-grabs
