### ISSUE TITLE
ReadonlyFieldAnalyzer: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by SanderSchutten** [code-cracker/code-cracker#873] opened 2017-02-03 10:14 UTC
#New analyzer:
ReadonlyFieldAnalyzer

#Bug

the analyzer ReadonlyFieldAnalyzer throws a NullReferenceException on code like this: 
public sealed class Class1
{
    private static readonly StringCollection s1 = new StringCollection
    {
            "1",
            "2"
    }
    private static readonly StringCollection s2 = new StringCollection
    {
            "1",
            "2"
    }
}

Codecrack version: 1.0.1 
Visual Studio 2015
Stacktrace:
System.NullReferenceException: Object reference not set to an instance of an object.
   at CodeCracker.CSharp.Usage.ReadonlyFieldAnalyzer.IsComplexValueType(SemanticModel semanticModel, FieldDeclarationSyntax fieldDeclaration)
   at CodeCracker.CSharp.Usage.ReadonlyFieldAnalyzer.GetCandidateVariables(SemanticModel semanticModel, FieldDeclarationSyntax fieldDeclaration)
   at CodeCracker.CSharp.Usage.ReadonlyFieldAnalyzer.GetCandidateVariables(SemanticModel semanticModel, IEnumerable`1 fieldDeclarations)
   at CodeCracker.CSharp.Usage.ReadonlyFieldAnalyzer.AnalyzeTree(SyntaxTreeAnalysisContext context, Compilation compilation)
   at CodeCracker.CSharp.Usage.ReadonlyFieldAnalyzer.<>c__DisplayClass8_0.<AnalyzeCompilation>b__0(SyntaxTreeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass41_0.<ExecuteSyntaxTreeActionsCore>b__0()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)

keep up the good work!

**Comment by MaStr11** [comment] 2017-02-27 15:03
I have written two test methods [here](https://github.com/code-cracker/code-cracker/compare/master...MaStr11:ReadonlyField) to reproduce the issue. The tests all pass without a NullReferenceException so I can't reproduce the issue. The fork was taken from the mater branch. If you like, I can create a pull request with the two tests-methods.

**Comment by giggio** [comment] 2017-03-11 19:01
I am not getting this error with the latest bits, this is probably already fixed. I also tried your tests, and they passed without the need for any other modification. So, I am closing the issue. If you can find a way to reproduce it let us know.

**Closed by giggio** 2017-03-11 19:01 UTC
Labels: bug, up-for-grabs

**Comment by arfmach** [comment] 2017-09-05 15:31
I get this error when I build my project.

`Warning AD0001: Analyzer 'CodeCracker.CSharp.Usage.ReadonlyFieldAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.`

Please let me know how I get the information needed to analyze the bug.

Visual Studio Community 2017 Version: 15.3.3
Code Cracker Version: 1.0.3

**Comment by giggio** [comment] 2017-09-28 19:01
@arfmach can you post the code that is generating the error?
