### ISSUE TITLE
CC0091 ASP.NET Application events cannot be static

### ISSUE THREAD

**Issue by AdrianoRNascimento** [code-cracker/code-cracker#555] opened 2015-10-15 19:20 UTC
The ASP.NET application events cannot be changed to static because they are not fired.

```
    public class WebApiApplication : System.Web.HttpApplication
    {
        protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();
            ...
            RouteConfig.RegisterRoutes(RouteTable.Routes);
        }
    }
```

My suggestion is to ignore this rule if the class inherits from System.Web.HttpApplication and the method name starts with "Application_" or "Session_".
In this [MSDN page](https://msdn.microsoft.com/en-us/library/ms178473(v=vs.100).aspx) is possible to see a list of application events.

**Comment by giggio** [comment] 2015-10-16 03:57
This is a duplicate of #451.

**Closed by giggio** 2015-10-16 03:57 UTC
