### ISSUE TITLE
BUG: CC0052 (Make readonly) sometimes detects complex value types

### ISSUE THREAD

**Issue by kindermannhubert** [code-cracker/code-cracker#854] opened 2016-12-06 11:55 UTC
Example:
```c#
    class C
    {
        private S s;

        public C()
        {
            s = default(S);
        }

        public void M1()
        {
            s.Value = 1;
        }

        public struct S
        {
            public int Value;
        }
    }
```
CC0052 is detected for "s" but this kind of change would break compilation.

Interesting is that in following two examples CC0052 is not detected (which is correct):
```c#
    class C
    {
        private S s;

        public C()
        {
            s = default(S);
        }

        public void M1()
        {
            s.Value = 1;
            Console.WriteLine(s);
        }

        public struct S
        {
            public int Value;
        }
    }
```
and
```c#
    class C
    {
        private S s = default(S);

        public void M1()
        {
            s.Value = 1;
        }

        public struct S
        {
            public int Value;
        }
    }
```

**Comment by GGG-KILLER** [comment] 2016-12-12 06:55
No, in fact, doing that would not break compilation at all, since `readonly` only prevents modifying the field itself, any properties or fields of the readonly field are still accessible and can be modified if allowed as shown on the code below:

```csharp
using System;
using System.Collections.Generic;

class MainClass
{
	public static void Main ( String[] args )
	{
		var t = new Test ( );
		t.Add ( "a" );
		t.Add ( "b" );
		t.Set ( "A" );
		Console.WriteLine ( t );
	}
}

class A
{
	public String Val;
}

class Test
{
	readonly IList<String> list;
	readonly A a;
	
	public Test ( )
	{
		list = new List<String> ( );
		a = new A ( );
	}
	
	public void Add ( Object value )
	{
		list.Add ( value.ToString ( ) );
	}
	
	public void Set ( Object value )
	{
		a.Val = value.ToString ( );
	}
	
	public override String ToString ( )
	{
		return "list: [" + String.Join ( ", ", list ) + "]"
		+ Environment.NewLine + "a: " + a.Val;
	}
}
```

Which results in:

> list: [a, b]
> a: A

Proof: https://repl.it/En1l

**Comment by giggio** [comment] 2017-01-07 19:13
Duplicate of #775.
Already fixed on #852.
A new diagnostic id was created and is disabled by default. See #808.

**Closed by giggio** 2017-01-07 19:13 UTC

**Comment by kindermannhubert** [comment] 2017-01-13 10:01
Sorry, but have tried the example I've submitted?
Now I tested it again with latest version of code-cracker from master branch and it still does not work.

**Comment by giggio** [comment] 2017-03-08 00:21
@kindermannhubert you are correct, it is not a duplicate.
