### ISSUE TITLE
CC0064: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by markusschaber** [code-cracker/code-cracker#579] opened 2015-11-04 10:52 UTC
The following Code generates the error "CC0064: Object reference not set to an instance of an object" on the line with the `IPAddress.Parse` call.
```
using System.Net;

namespace CodeCrackerTest
{
    class Program
    {
        static void Main(string[] args)
        {
            IPAddress ipaddress = null;

            var stTemp = args[0].ToString();

            if (stTemp == "localhost")
                stTemp = "127.0.0.1";

            ipaddress = IPAddress.Parse(stTemp);
        }
    }
}
```
I cannot see how the call to `Parse()` should generate a Null reference exception - stTemp is guaranteed not to be null.

**Comment by giggio** [comment] 2015-11-04 17:14
This is a duplicate of #571. @andrecarlucci is working on it.

**Closed by giggio** 2015-11-04 17:14 UTC

**Comment by markusschaber** [comment] 2015-11-04 21:27
Sorry for the duplicate - I searched using several different search terms (like "IPAddress Parse Null reference exception", and did not find the other entry.
